export enum ExceptionTableCardActionType{
  LOAD_DATA = "EXCEPTION_TABLE_CARD_LOAD_DATA",
  LOAD_DATA_SUCCESS = "EXCEPTION_TABLE_CARD_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "EXCEPTION_TABLE_CARD_LOAD_DATA_ERROR",
}