export enum VisitsStatisticalActionType{
  CHANGE_SEARCH_DATE = "VISITS_STATISTICAL_CHANGE_SEARCH_DATE",
  LOAD_DATA = "VISITS_STATISTICAL_LOAD_DATA",
  LOAD_DATA_SUCCESS = "VISITS_STATISTICAL_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "VISITS_STATISTICAL_LOAD_LOAD_DATA_ERROR"
}