export enum AppActionType {
  FETCH_ALL_SCHOOL_SIMPLE_INFO = 'FETCH_ALL_SCHOOL_SIMPLE_INFO',
  FETCH_ALL_SCHOOL_SIMPLE_INFO_SUCCESS = 'FETCH_ALL_SCHOOL_SIMPLE_INFO_SUCCESS',
  FETCH_UNPURCHASED_SCHOOL_SIMPLE_INFO = 'FETCH_UNPURCHASED_SCHOOL_SIMPLE_INFO',
  FETCH_UNPURCHASED_SCHOOL_SIMPLE_INFO_SUCCESS = 'FETCH_UNPURCHASED_SCHOOL_SIMPLE_INFO_SUCCESS',
}