export enum WiseBoardActionType{
  FETCH_LIST = 'WISE_BOARD_FETCH_LIST',
  FETCH_LIST_SUCCESS = 'WISE_BOARD_FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR = 'WISE_BOARD_FETCH_LIST_ERROR',
  CHANGE_SEARCH_SCHOOL_NAME = 'WISE_BOARD_CHANGE_SEARCH_SCHOOL_NAME',
  CHANGE_SERVICE_TYPE = 'WISE_BOARD_CHANGE_SERVICE_TYPE',
  OPEN_ADD_LAYER = 'WISE_BOARD_OPEN_ADD_LAYER',
  CLOSE_ADD_LAYER = 'WISE_BOARD_CLOSE_ADD_LAYER',
  CLEAR_ADD_LAYER = 'WISE_BOARD_CLEAR_ADD_LAYER',
  ADD_WISE_BOARD_SCHOOL_ID_CHANGE = 'ADD_WISE_BOARD_SCHOOL_ID_CHANGE',
  ADD_WISE_BOARD_SERVICE_TYPE_CHANGE = 'ADD_WISE_BOARD_SERVICE_TYPE_CHANGE',
  ADD_WISE_BOARD_BUY_CALL_TIME_CHANGE = 'ADD_WISE_BOARD_BUY_CALL_TIME_CHANGE',
}