export enum WiseBoardActionType{
  FETCH_WISE_BOARD_LIST = 'FETCH_WISE_BOARD_LIST',
  FETCH_WISE_BOARD_LIST_SUCCESS = 'FETCH_WISE_BOARD_LIST_SUCCESS',
  FETCH_WISE_BOARD_LIST_ERROR = 'FETCH_WISE_BOARD_LIST_ERROR',
  CHANGE_CURRENT_PAGE = 'WISE_BOARD_CHANGE_CURRENT_PAGE'
}