export enum WiseBoardListActionType{
  FETCH_LIST = 'WISE_BOARD_FETCH_LIST',
  FETCH_LIST_SUCCESS = 'WISE_BOARD_FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR = 'WISE_BOARD_FETCH_LIST_ERROR',
  CHANGE_SEARCH_SCHOOL_NAME = 'WISE_BOARD_CHANGE_SEARCH_SCHOOL_NAME',
  CHANGE_SERVICE_TYPE = 'WISE_BOARD_CHANGE_SERVICE_TYPE',
}