export enum MessageRecordActionType{
  CHANGE_CURRENT_PAGE = "MESSAGE_RECORD_ACTION_TYPE_CHANGE_CURRENT_PAGE",
  LOAD_DATA = "MESSAGE_RECORD_ACTION_TYPE_LOAD_DATA",
  LOAD_DATA_SUCCESS = "MESSAGE_RECORD_ACTION_TYPE_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "MESSAGE_RECORD_ACTION_TYPE_LOAD_DATA_ERROR",
}