export enum DataOverviewActionType{
  CHANGE_SEARCH_DATE = "DATA_OVERVIEW_CHANGE_SEARCH_DATE",
  LOAD_DATA = "DATA_OVERVIEW_LOAD_DATA",
  LOAD_DATA_SUCCESS = "DATA_OVERVIEW_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "DATA_OVERVIEW_LOAD_DATA_ERROR"
}