export enum MiniProgramStatisticalActionType{
  CHANGE_SEARCH_DATE = "MINI_PROGRAM_STATISTICAL_CHANGE_SEARCH_DATE",
  LOAD_DATA = "MINI_PROGRAM_STATISTICAL_LOAD_DATA",
  LOAD_DATA_SUCCESS = "MINI_PROGRAM_STATISTICAL_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "MINI_PROGRAM_STATISTICAL_LOAD_DATA_ERROR"
}