export enum LogMgActionType{
  CHANGE_SEARCH_STR = "LOG_MG_CHANGE_SEARCH_STR",
  CHANGE_CURRENT_PAGE = "LOG_MG_CHANGE_CURRENT_PAGE",
  LOAD_DATA = "LOG_MG_LOAD_DATA",
  LOAD_SUCCESS = "LOG_MG_LOAD_SUCCESS",
  LOAD_ERROR = "LOG_MG_LOAD_ERROR"
}