export enum ExceptionStatisticalActionType{
  CHANGE_SEARCH_DATE = "EXCEPTION_STATISTICAL_CHANGE_SEARCH_DATE",
  LOAD_DATA = "EXCEPTION_STATISTICAL_LOAD_DATA",
  LOAD_DATA_SUCCESS = "EXCEPTION_STATISTICAL_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "EXCEPTION_STATISTICAL_LOAD_DATA_ERROR"
}