export enum RealtimePushTableCardActionType{
  LOAD_DATA = "REALTIME_PUSH_TABLE_CARD_LOAD_DATA",
  LOAD_DATA_SUCCESS = "REALTIME_PUSH_TABLE_CARD_LOAD_DATA_SUCCESS",
  LOAD_DATA_ERROR = "REALTIME_PUSH_TABLE_CARD_LOAD_DATA_ERROR",
}