export enum RechargeRecordActionType{
  OPEN_LAYER = "RECHARGE_RECORD_OPEN_LAYER",
  CLOSE_LAYER = "RECHARGE_RECORD_CLOSE_LAYER",
  FETCH_LIST = "RECHARGE_RECORD_FETCH_LIST",
  FETCH_LIST_ERROR = "RECHARGE_RECORD_FETCH_LIST_ERROR",
  FETCH_LIST_SUCCESS = "RECHARGE_RECORD_FETCH_LIST_SUCCESS",
}