export enum UserMgActionType{
    CHANGE_SEARCH_STR = "USER_MG_CHANGE_SEARCH_STR",
    CHANGE_SCHOOL_ID = "USER_MG_CHANGE_SCHOOL_ID",
    CHANGE_CURRENT_PAGE = "USER_MG_CHANGE_CURRENT_PAGE",
    LOAD_DATA = "USER_MG_LOAD_DATA",
    LOAD_DATA_SUCCESS = "USER_MG_LOAD_DATA_SUCCESS",
    LOAD_DATA_ERROR = "USER_MG_LOAD_DATA_ERROR",
}