export enum RechargeLayerActionType{
  OPEN_RECHARGE_LAYER = 'WISE_BOARD_OPEN_RECHARGE_LAYER',
  CLOSE_RECHARGE_LAYER = 'WISE_BOARD_CLOSE_RECHARGE_LAYER',
  CLEAR_RECHARGE_LAYER = 'WISE_BOARD_CLEAR_RECHARGE_LAYER',
  RECHARGE_LAYER_RECHARGE_TIME_CHANGE = 'WISE_BOARD_RECHARGE_LAYER_RECHARGE_TIME_CHANGE',
  RECHARGE_LAYER_RECHARGE_REMARK_CHANGE = 'WISE_BOARD_RECHARGE_LAYER_RECHARGE_REMARK_CHANGE'
}