export enum AddLayerActionType{
  OPEN_ADD_LAYER = 'WISE_BOARD_OPEN_ADD_LAYER',
  CLOSE_ADD_LAYER = 'WISE_BOARD_CLOSE_ADD_LAYER',
  CLEAR_ADD_LAYER = 'WISE_BOARD_CLEAR_ADD_LAYER',
  ADD_WISE_BOARD_SCHOOL_ID_CHANGE = 'ADD_WISE_BOARD_SCHOOL_ID_CHANGE',
  ADD_WISE_BOARD_SERVICE_TYPE_CHANGE = 'ADD_WISE_BOARD_SERVICE_TYPE_CHANGE',
  ADD_WISE_BOARD_BUY_CALL_TIME_CHANGE = 'ADD_WISE_BOARD_BUY_CALL_TIME_CHANGE',
}